if (NOT APPLE)
    link_directories(${_qt5Core_install_prefix}/lib)
    set (Qt5Widgets_LIBRARIES -lQt5Widgets)
    set (Qt5Gui_LIBRARIES -lQt5Gui)
    if (PLATFORM_NAME STREQUAL "NaCl" OR PLATFORM_NAME STREQUAL "PNaCl")
        set (Qt5Gui_LIBRARIES -lQt5Gui -lqtharfbuzzng)
    endif (PLATFORM_NAME STREQUAL "NaCl" OR PLATFORM_NAME STREQUAL "PNaCl")
    set (Qt5Core_LIBRARIES -lQt5Core)
    set (Qt5Network_LIBRARIES -lQt5Network)
    set (Qt5Svg_LIBRARIES -lQt5Svg)
endif (NOT APPLE)
